# Generated by Django 6.0.1 on 2026-02-21 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text="Required. 150 characters or fewer. Letters, digits, spaces and @/./+/-/_/' only.", max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message="Enter a valid username. This value may contain letters, numbers, spaces, and @/./+/-/_/' characters.", regex="^[\\w.@+\\- ']+$")]),
        ),
    ]
